import{a as S,S as q,i}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const v="52337291-0776378263373b49cfa64027e",C="https://pixabay.com/api/",m=15;async function P(o,t=1){try{const n={key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:m,page:t};return(await S.get(C,{params:n})).data}catch(n){throw n}}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more");let E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function A(o){const t=o.map(({webformatURL:n,largeImageURL:a,tags:e,likes:r,views:s,comments:w,downloads:b})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${n}" alt="${e}" />
        </a>
        <div class="info">
          <p>❤️ ${r}</p>
          <p>👁️ ${s}</p>
          <p>💬 ${w}</p>
          <p>⬇️ ${b}</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",t),E.refresh()}function B(){p.innerHTML=""}function R(){g.classList.remove("hidden")}function $(){g.classList.add("hidden")}function M(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}const d=document.querySelector(".form"),O=d.querySelector("input[name='search-text']"),u=document.querySelector(".load-more"),x=document.querySelector(".gallery");let y="",l=1,f=0;d.addEventListener("submit",async o=>{o.preventDefault();const t=O.value.trim();t?(y=t,l=1,B(),c(),await L()):i.warning({message:"Please enter a search query!",position:"topRight",backgroundColor:"#ff7fa0",messageColor:"#2e2f42",width:280,timeout:4e3}),d.reset()});u.addEventListener("click",async()=>{l+=1,await L(),I()});async function L(){R(),c(),u.disabled=!0;try{const{hits:o,totalHits:t}=await P(y,l);if(f=t,!o.length){c(),i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ff7fa0",messageColor:"#2e2f42",width:320,timeout:4e3});return}A(o),l*m<f?M():(c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#ff7fa0",messageColor:"#2e2f42",width:360,timeout:5e3}))}catch{i.error({title:"Error",message:"Something went wrong. Try again later!",position:"topRight",backgroundColor:"#ff7fa0",titleColor:"#2e2f42",messageColor:"#2e2f42",width:320,timeout:4e3})}finally{$(),u.disabled=!1}}function I(){const o=x.querySelector(".gallery-item");if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
